{
 "title": "selenium grid",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "selenium-hub", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "http queue",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "queueSize{service_name=\"selenium-hub\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "http active requests ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "http_server_active_requests{service_name=\"selenium-hub\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "trace duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    { "service": "selenium-hub" }
   ]
  },
  {
   "title": "http requests - responses",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "{service_name=\"selenium-hub\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "{servicename=\"selenium-hub\"} |json"
    }
   ]
  },
  {
   "title": "trace duration",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "targets": [
    { "service": "selenium-hub" }
   ]
  },
  {
   "title": "logs - warnings + errors",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "{servicename=\"selenium-hub\"} | json |severity=\"WARNING\" or severity=\"ERROR\""
    }
   ]
  },
  { "title": "Chrome", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "http requests - responses",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum by(__name__)({le=\"+Inf\",service_name=\"selenium-node-chrome\"})",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "http return codes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "sum by (http_status_code)({le=\"+Inf\",service_name=\"selenium-node-chrome\",http_status_code!=\"\"})",
     "legendFormat": "{{http_status_code}}"
    }
   ]
  },
  {
   "title": "trace duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "targets": [
    { "service": "selenium-node-chrome" }
   ]
  },
  {
   "title": "traces table",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "targets": [
    { "service": "selenium-node-chrome" }
   ]
  },
  {
   "title": "logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "{servicename=\"selenium-node-chrome\"} | json"
    }
   ]
  },
  {
   "title": "logs - warnings + errors",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "{servicename=\"selenium-node-chrome\"} | json |severity=\"WARNING\" or severity=\"ERROR\""
    }
   ]
  }
 ]
}