SHELL := /bin/bash

.PHONY: clean prepare-fem-tests

ifndef $(LEGACY)
LEGACY = false
endif

prepare-fem-tests:
	@mkdir -p target/tests
	@cp -rn tests target/

run: prepare-fem-tests
ifeq ($(LEGACY), true)
	docker-compose --file target/tests/docker-compose-fem-tests.yml --project-name fem up --build
else
	docker compose --file target/tests/docker-compose-fem-tests.yml --project-name fem up --build
endif

clean:
	@rm -rf target/tests
