SHELL := /bin/bash

.PHONY: clean prepare-fem-dbexporter-mongodb prepare-fem-dbexporter-postgresql config-mongodb config-postgresql

ifndef $(LEGACY)
LEGACY = false
endif

prepare-fem-dbexporter-mongodb:
	@mkdir -p target/dbexporter
	@cp -rn dbexporter/docker-compose-fem-dbexporter-mongodb.yml target/dbexporter

prepare-fem-dbexporter-postgresql:
	@mkdir -p target/dbexporter
	@cp -rn dbexporter/docker-compose-fem-dbexporter-postgresql.yml target/dbexporter

config-mongodb: prepare-fem-dbexporter-mongodb
	@echo "mongodb username: "; \
	read USERNAME; \
	sed -i "s/{mongodb_username}/$$USERNAME/" target/dbexporter/docker-compose-fem-dbexporter-mongodb.yml

	@echo "mongodb password: "; \
	read -s PASSWORD; \
	sed -i "s/{mongodb_password}/$$PASSWORD/" target/dbexporter/docker-compose-fem-dbexporter-mongodb.yml

	@echo "mongodb host list (format: host:port[,host:port]): "; \
	read HOSTS; \
	sed -i "s/{mongodb_hosts}/$$HOSTS/" target/dbexporter/docker-compose-fem-dbexporter-mongodb.yml

config-postgresql: prepare-fem-dbexporter-postgresql
	@echo "postgresql username: "; \
	read USERNAME; \
	sed -i "s/{postgresql_username}/$$USERNAME/" target/dbexporter/docker-compose-fem-dbexporter-postgresql.yml

	@echo "postgresql password: "; \
	read -s PASSWORD; \
	sed -i "s/{postgresql_password}/$$PASSWORD/" target/dbexporter/docker-compose-fem-dbexporter-postgresql.yml

	@echo "postgresql host list (format: host:port[,host:port]): "; \
	read HOSTS; \
	sed -i "s/{postgresql_hosts}/$$HOSTS/" target/dbexporter/docker-compose-fem-dbexporter-postgresql.yml

start-mongodb: prepare-fem-dbexporter-mongodb
	@echo "Please ensure to call 'config-mongodb' before starting"
ifeq ($(LEGACY), true)
	docker-compose --file target/dbexporter/docker-compose-fem-dbexporter-mongodb.yml --project-name fem up -d
else
	docker compose --file target/dbexporter/docker-compose-fem-dbexporter-mongodb.yml --project-name fem up -d
endif

stop-mongodb: prepare-fem-dbexporter-mongodb
ifeq ($(LEGACY), true)
	docker-compose --file target/dbexporter/docker-compose-fem-dbexporter-mongodb.yml --project-name fem down
else
	docker compose --file target/dbexporter/docker-compose-fem-dbexporter-mongodb.yml --project-name fem down
endif

start-postgresql: prepare-fem-dbexporter-postgresql
	@echo "Please ensure to call 'config-postgresql' before starting"
ifeq ($(LEGACY), true)
	docker-compose --file target/dbexporter/docker-compose-fem-dbexporter-postgresql.yml --project-name fem up -d
else
	docker compose --file target/dbexporter/docker-compose-fem-dbexporter-postgresql.yml --project-name fem up -d
endif

stop-postgresql: prepare-fem-dbexporter-postgresql
ifeq ($(LEGACY), true)
	docker-compose --file target/dbexporter/docker-compose-fem-dbexporter-postgresql.yml --project-name fem down
else
	docker compose --file target/dbexporter/docker-compose-fem-dbexporter-postgresql.yml --project-name fem down
endif

clean: stop-postgresql stop-mongodb
	@rm -rf target/dbexporter
