SHELL := /bin/bash

prepare-fem-shellexporter:
	@mkdir -p target/shellexporter
	@cp -rn shellexporter target

start: prepare-fem-shellexporter
	docker-compose --file target/shellexporter/docker-compose-fem-shellexporter.yml --project-name fem up -d

stop: prepare-fem-shellexporter
	docker-compose --file target/shellexporter/docker-compose-fem-shellexporter.yml --project-name fem down

clean: stop
	@rm -rf target/shellexporter
