SHELL := /bin/bash

target:
	@mkdir -p target/dbexporter

docker-fem-dbexporter-mongodb: target
	@cp -n dbexporter/docker-compose-fem-dbexporter-mongodb.yml target/dbexporter

docker-fem-dbexporter-postgresql: target
	@cp -n dbexporter/docker-compose-fem-dbexporter-postgresql.yml target/dbexporter

config-mongodb: docker-fem-dbexporter-mongodb
	@echo "mongodb username: "; \
	read USERNAME; \
	sed -i "s/{mongodb_username}/$$USERNAME/" target/dbexporter/docker-compose-fem-dbexporter-mongodb.yml

	@echo "mongodb password: "; \
	read -s PASSWORD; \
	sed -i "s/{mongodb_password}/$$PASSWORD/" target/dbexporter/docker-compose-fem-dbexporter-mongodb.yml

	@echo "mongodb host list (format: host:port[,host:port]): "; \
	read HOSTS; \
	sed -i "s/{mongodb_hosts}/$$HOSTS/" target/dbexporter/docker-compose-fem-dbexporter-mongodb.yml

config-postgresql: docker-fem-dbexporter-postgresql
	@echo "postgresql username: "; \
	read USERNAME; \
	sed -i "s/{postgresql_username}/$$USERNAME/" target/dbexporter/docker-compose-fem-dbexporter-postgresql.yml

	@echo "postgresql password: "; \
	read -s PASSWORD; \
	sed -i "s/{postgresql_password}/$$PASSWORD/" target/dbexporter/docker-compose-fem-dbexporter-postgresql.yml

	@echo "postgresql host list (format: host:port[,host:port]): "; \
	read HOSTS; \
	sed -i "s/{postgresql_hosts}/$$HOSTS/" target/dbexporter/docker-compose-fem-dbexporter-postgresql.yml

start-mongodb: docker-fem-dbexporter-mongodb
	@echo "Please ensure to call 'config-mongodb' before starting"
	docker compose --file target/dbexporter/docker-compose-fem-dbexporter-mongodb.yml up -d

stop-mongodb: docker-fem-dbexporter-mongodb
	docker compose --file target/dbexporter/docker-compose-fem-dbexporter-mongodb.yml down

start-postgresql: docker-fem-dbexporter-postgresql
	@echo "Please ensure to call 'config-postgresql' before starting"
	docker compose --file target/dbexporter/docker-compose-fem-dbexporter-postgresql.yml up -d

stop-postgresql: docker-fem-dbexporter-postgresql
	docker compose --file target/dbexporter/docker-compose-fem-dbexporter-postgresql.yml down

clean:
	@rm -rf target/dbexporter