version: "3.8"

networks:
  monitoring:

volumes:
  fem_grafana_data:
  fem_loki_data:
  fem_opensearch_data:
  fem_prometheus_data:

services:
  fem_jaeger-collector:
    image: jaegertracing/jaeger-collector:1.54
    restart: unless-stopped
    container_name: fem_jaeger-collector
    hostname: fem_jaeger-collector
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
    command: [
        "--es.server-urls=http://fem_opensearch:9200",
        "--es.num-shards=1",
        "--es.num-replicas=0",
        "--es.version=7",
        "--log-level=info"
    ]
    networks:
      - monitoring
    depends_on:
      - fem_opensearch
  fem_jaeger-query:
    image: jaegertracing/jaeger-query:1.54
    restart: unless-stopped
    container_name: fem_jaeger-query
    hostname: fem_jaeger-query
    ports:
      - "26686:16686" #ui, notls
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
    command: [
        "--es.server-urls=http://fem_opensearch:9200",
        "--es.num-shards=1",
        "--es.num-replicas=0",
        "--es.version=7",
        "--log-level=info"
    ]
    networks:
      - monitoring
    depends_on:
      - fem_opensearch
  fem_opensearch:
    image: opensearchproject/opensearch:2.11.1
    restart: unless-stopped
    container_name: fem_opensearch
    hostname: fem_opensearch
    environment:
      - cluster.name=fem-cluster
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - plugins.security.disabled=true # disable tls which is enabled by default
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx6144m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - fem_opensearch_data:/usr/share/opensearch/data
    networks:
      - monitoring
  fem_opensearch_exporter:
    image: prometheuscommunity/elasticsearch-exporter:v1.7.0
    restart: unless-stopped
    container_name: fem_opensearch_exporter
    hostname: fem_opensearch_exporter
    command:
     - '--es.uri=http://fem_opensearch:9200'
    networks:
      - monitoring
    depends_on:
      - fem_opensearch
  fem_jaeger-es-cleaner:
    image: jaegertracing/jaeger-es-index-cleaner:1.54
    container_name: fem_opensearch-cleaner
    hostname: fem_opensearch-cleaner
    command: [
      "7",
      "http://fem_opensearch:9200"
    ]
    networks:
      - monitoring
    depends_on:
      - fem_opensearch
  fem_prometheus:
    image: prom/prometheus:v2.49.1
    restart: unless-stopped
    container_name: fem_prometheus
    hostname: fem_prometheus
    ports:
      - "29090:9090" #ui, notls
    volumes:
      - $PWD/target/fem/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - fem_prometheus_data:/prometheus
    networks:
      - monitoring
    depends_on:
      - fem_opensearch
  fem_grafana:
    image: grafana/grafana:10.3.3
    restart: unless-stopped
    container_name: fem_grafana
    hostname: fem_grafana
    ports:
      - "23000:3000" #ui, notls
    volumes:
      - fem_grafana_data:/var/lib/grafana
      - $PWD/target/fem/config/grafana-dashboard-templates:/var/lib/grafana-dashboard-templates
      - $PWD/target/fem/config/grafana-provisioning:/etc/grafana/provisioning
    networks:
      - monitoring
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.entrypoints=https"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.rule=Host(`fem_grafana`)"
  fem_otel-collector:
    image: otel/opentelemetry-collector-contrib:0.94.0
    restart: unless-stopped
    container_name: fem_otel-collector
    hostname: fem_otel-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - $PWD/target/fem/config/otel-collector-fem-config.yml:/etc/otel-collector-config.yml:ro
      - $PWD/target/fem/certs:/tmp/certs:ro
    ports:
      - "24318:4318"  # grpc, tls
    networks:
      - monitoring
  fem_loki:
    image: grafana/loki:main
    restart: unless-stopped
    container_name: fem_loki
    hostname: fem_loki
    command: -config.file=/etc/loki/config.yml
    volumes:
      - $PWD/target/fem/config/loki-config.yml:/etc/loki/config.yml:ro
      - fem_loki_data:/tmp
    ports:
      - 23100:3100 #api, notls
    networks:
      - monitoring
  fem_traefik:
    image: traefik:v2.11.0
    restart: unless-stopped
    container_name: fem_traefik
    hostname: fem_traefik
    ports:
      - "20080:80"
      - "20443:443"
      - "28080:8080"
    networks:
      - monitoring
    volumes:
      - $PWD/target/fem/config/traefik.yml:/etc/traefik/traefik.yml:ro
      - $PWD/target/fem/config/traefik-certs.yml:/etc/traefik/traefik-certs.yml:ro
      - $PWD/target/fem/certs:/etc/traefik/certs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
