version: "3.8"

networks:
  monitoring:

volumes:
  grafana_data:
  loki_data:
  opensearch_data:
  prometheus_data:

services:
  fem_jaeger_collector:
    image: jaegertracing/jaeger-collector:1.63.0
    read_only: true
    cap_drop:
      - ALL
    restart: unless-stopped
    container_name: fem_jaeger_collector
    hostname: fem-jaeger-collector
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
    command: [
        "--es.server-urls=http://fem-opensearch:9200",
        "--es.num-shards=1",
        "--es.num-replicas=0",
        "--es.version=7",
        "--log-level=info"
    ]
    networks:
      - monitoring
    depends_on:
      - fem_opensearch
  fem_jaeger_query:
    image: jaegertracing/jaeger-query:1.63.0
    read_only: true
    cap_drop:
      - ALL
    restart: unless-stopped
    container_name: fem_jaeger_query
    hostname: fem-jaeger-query
    ports:
      - "26686:16686" #ui, notls
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
    command: [
        "--es.server-urls=http://fem-opensearch:9200",
        "--es.num-shards=1",
        "--es.num-replicas=0",
        "--es.version=7",
        "--log-level=info"
    ]
    networks:
      - monitoring
    depends_on:
      - fem_opensearch
  fem_opensearch:
    image: opensearchproject/opensearch:2.18.0
    cap_drop:
      - ALL
    restart: unless-stopped
    container_name: fem_opensearch
    hostname: fem-opensearch
    environment:
      - cluster.name=fem-cluster
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - plugins.security.disabled=true # disable tls which is enabled by default
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx6144m"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=F_E_M_rules_the_world_since_2022!"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    networks:
      - monitoring
  fem_opensearch_exporter:
    image: prometheuscommunity/elasticsearch-exporter:v1.8.0
    read_only: true
    cap_drop:
      - ALL
    restart: unless-stopped
    container_name: fem_opensearch_exporter
    hostname: fem-opensearch-exporter
    command:
     - '--es.uri=http://fem-opensearch:9200'
    networks:
      - monitoring
    depends_on:
      - fem_opensearch
  fem_jaeger_es_cleaner:
    image: jaegertracing/jaeger-es-index-cleaner:1.63.0
    read_only: true
    cap_drop:
      - ALL
    container_name: fem_jaeger_es_cleaner
    hostname: fem-opensearch-cleaner
    command: [
      "7",
      "http://fem-opensearch:9200"
    ]
    networks:
      - monitoring
    depends_on:
      - fem_opensearch
  fem_prometheus:
    image: prom/prometheus:v2.55.1
    read_only: true
    cap_drop:
      - ALL
    restart: unless-stopped
    container_name: fem_prometheus
    hostname: fem-prometheus
    ports:
      - "29090:9090" #ui, notls
    volumes:
      - prometheus_data:/prometheus
      - $PWD/target/fem/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - monitoring
    depends_on:
      - fem_opensearch
  fem_grafana:
    image: grafana/grafana:11.3.1
    read_only: true
    cap_drop:
      - ALL
    restart: unless-stopped
    container_name: fem_grafana
    hostname: fem-grafana
    ports:
      - "23000:3000" #ui, notls
    volumes:
      - grafana_data:/var/lib/grafana
      - $PWD/target/fem/config/grafana-dashboard-templates:/var/lib/grafana-dashboard-templates
      - $PWD/target/fem/config/grafana-provisioning:/etc/grafana/provisioning
    networks:
      - monitoring
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=monitoring"
      - "traefik.http.routers.grafana.entrypoints=https"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.fem.localhost`)"
    extra_hosts:
      - "grafana.fem:127.0.0.1"
  fem_otel-collector:
    image: otel/opentelemetry-collector-contrib:0.114.0
    read_only: true
    cap_drop:
      - ALL
    restart: unless-stopped
    container_name: fem_otel-collector
    hostname: fem-otel-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - $PWD/target/fem/config/otel-collector-fem-config.yml:/etc/otel-collector-config.yml:ro
      - $PWD/target/fem/certs:/tmp/certs:ro
    ports:
      - "24318:4318"  # grpc, tls
    networks:
      - monitoring
  fem_loki:
    image: grafana/loki:main
    read_only: true
    cap_drop:
      - ALL
    restart: unless-stopped
    container_name: fem_loki
    hostname: fem-loki
    command: -config.file=/etc/loki/config.yml
    volumes:
      - loki_data:/tmp
      - $PWD/target/fem/config/loki-config.yml:/etc/loki/config.yml:ro
    ports:
      - 23100:3100 #api, notls
    networks:
      - monitoring
  fem_traefik:
    image: traefik:v3.2.1
    read_only: true
    cap_drop:
      - ALL
    restart: unless-stopped
    container_name: fem_traefik
    hostname: fem-traefik
    ports:
      - "20080:80"
      - "20443:443"
      - "28080:8080"
    networks:
      - monitoring
    volumes:
      - $PWD/target/fem/config/traefik.yml:/etc/traefik/traefik.yml:ro
      - $PWD/target/fem/config/traefik-certs.yml:/etc/traefik/traefik-certs.yml:ro
      - $PWD/target/fem/certs:/etc/traefik/certs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
