@startuml
left to right direction

node "remote-unix-host" {
  [shellexporter] - 9360

}

node "monitoring-host" {
  package "metrics" {
    [Prometheus] ..> 9360
    [Prometheus] - PrometheusHttp
  }

  package "grafana" {
    [Grafana] - GrafanaUI
    [Grafana] ..> PrometheusHttp
  }
}
@enduml
