@startuml

left to right direction

node "application-host" {
  component application {
      [Otel Agent] ..> OtelAgentGrpc
  }
}

node "monitoring-host" {
  package "exporter" {
    [Otel Collector] - OtelAgentGrpc
    [Otel Collector] --> [Jaeger Exporter]
    [Otel Collector] --> [Loki Exporter]
    [Otel Collector] --> [Prometheus Exporter]

    [Loki Exporter] ..> LokiHttp

    [Jaeger Exporter] ..> JaegerCollectorHttp

    [Prometheus Exporter] - PrometheusExporterHttp
  }

  package "traces" {
    [Opensearch] - OpensearchHttp
    [Opensearch] ..> Filesystem

    [Jaeger Collector] - JaegerCollectorHttp
    [Jaeger Collector] ..> OpensearchHttp
    [Jaeger Query] ..> OpensearchHttp
    [Jaeger Query] - JaegerQueryHttp
    [Jaeger Query] - JaegerQueryUI
  }

  package "logs" {
    [Loki] - LokiHttp
    [Loki] ..> Filesystem
  }

  package "metrics" {
    [Prometheus] ..> Filesystem
    [Prometheus] ..> PrometheusExporterHttp
    [Prometheus] - PrometheusHttp
  }

  package "grafana" {
    [Grafana] - GrafanaUI
    [Grafana] ..> PrometheusHttp
    [Grafana] ..> JaegerQueryHttp
    [Grafana] ..> Filesystem
  }

  [Traefik] ..> GrafanaUI
  [Traefik] - TraefikHttps
  [Traefik] - TraefikHttp
  [Traefik] - TraefikDashboard
}

node "user-host" {
  [Browser] ..> TraefikHttps
}

node "Filesystem" {
}

@enduml