{
 "title": "demoapp",
 "description": "demoapp connected by otelagent",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "trace duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "service": "demoapp" }
   ]
  },
  {
   "title": "trace duration descending",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "service": "demoapp" }
   ]
  },
  {
   "title": "runtime exceptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{exception=\"RuntimeException\",exported_job=\"demoapp\"}",
     "legendFormat": "{{exception}}"
    }
   ]
  },
  {
   "title": "logfile - exceptions",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "{job=\"demoapp\", level=\"ERROR\"} |= ``"
    }
   ]
  },
  {
   "title": "http status code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by(http_status_code)({exported_job=\"demoapp\",http_status_code!=\"\"})",
     "legendFormat": "{{http_status_code}}"
    }
   ]
  },
  {
   "title": "logfile - app start duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum_over_time({job=\"demoapp\"} |~\"Started PetClinicApplication\" | json | line_format \"{{.body}}\" | pattern `Started PetClinicApplication in <starttime> <_>` | unwrap starttime [1m])",
     "legendFormat": "container: {{hostname}}, pid: {{resources_process_pid}}"
    }
   ]
  }
 ]
}